### ISSUE TITLE
Add CRAN package kwb.hantush

### ISSUE THREAD

**Issue by mrustl** [datacamp/tutorial#10]
Great work @filipsch to make R markdown interactive ! 

I would love to use it for my CRAN package "kwb.hantush" on your server so I can test it out!

**Comment by filipsch** [comment]
Hi, `kwb.hantush` is scheduled to install so it should be available on DataCamp's R servers in about an hour. Like I mentioned in the talk: we're working on making package management easier for DataCamp Light, so stay tuned!
