### ISSUE TITLE
Add plot() feature 

### ISSUE THREAD

**Issue by mrustl** [datacamp/tutorial#11]
Executing code works nicely using the tutorial package. However, a very important feature is still missing: support for plotting. 

Do you plan to integrate this feature or are you already working on it?

**Comment by filipsch** [comment]
@mrustl Yes we are working on this! Hope to have it by the end of this month at the latest!

**Comment by filipsch** [comment]
Hey! The current master tip of `tutorial` refers to the latest version of DataCamp Light, that features plots. It is not yet possible to zoom in and out on plots, or to watch them seperately, only in your widget. To make sure your plots look decent, you can set the `height` attribute of `go_interactive()` to make your DataCamp Light windows large enough.

**Comment by filipsch** [comment]
(to experiment, use `devtools::install_github("datacamp/tutorial")` to install the latest version)
