### ISSUE TITLE
Make knitted html not selfcontained

### ISSUE THREAD

**Issue by EvertEt** [datacamp/tutorial#13]
`output: 
  html_document:
    self_contained: no`

**Comment by filipsch** [comment]
This is not possible in `knitr`:
https://github.com/yihui/knitr/issues/1246
so I'll update the README and the vignettes and the examples to include this `self_contained: false` thing.

**Comment by filipsch** [comment]
@EvertEt At second thought, this is going to be highly subideal if we want people to use this stuff easily. Can you maybe look into the reason why it doesn't work in self_contained mode?

**Comment by filipsch** [comment]
@EvertEt the current status is: if I knit the file, in self-contained mode (which is the default, when you don't mention the `self_contained` options), then the RStudio viewer opens, but the dcl frame does not render. If I then right click and reload it renders. If I open in browser, it also renders.

**Comment by EvertEt** [comment]
@filipsch Could you try again if this issue still persists? (And all other issues)
I can't test the HTML viewer because of SSL errors in RStudio.

**Comment by filipsch** [comment]
@EvertEt superstrange stuff:
- The first time I hit 'knit html', the DCL window renders, but I can't run code (don't get a session).
- If I knit the file again, the DCL window doesn't render anymore (also not on reload).
It is clear that this stuff is only causing issues inside the RStudio viewer so I wouldn't focus on this too much if it's such a pain.

**Comment by EvertEt** [comment]
@filipsch Do you get any errors in the console (right-click, inspect, console)?
Is the loader still there after reload? And the 1px blue border?

Maybe we could look at this together friday because I can't investigate this without Rstudio?

Thanks for testing!

**Comment by filipsch** [comment]
@EvertEt Can't you just get RStudio to work? :) This is highly inefficient.
If it's absolutely necessary, we can do it together on Friday.

**Comment by EvertEt** [comment]
@filipsch I do get a session on the first try so that will be a pain to figure out why you don't.
I don't have the same loading behaviour as you describe but it still does weird things, never load, only after reload, only before reload,... I will debug this now.
