### ISSUE TITLE
"Your session has been disconnected"

### ISSUE THREAD

**Issue by rubenarslan** [datacamp/tutorial#15]
I keep getting this, even in the example. It's somewhat random.
I tried disabling extensions, making sure I always only had one datacamp tab open.

What are possible causes? In the console I see 403s from the multiplexer subdomain that only seem to co-occur with the disconnected message. But I don't why there are sometimes 403s and sometimes not.

**Comment by filipsch** [comment]
Hey @rubenarslan can you give some more details on how you tried this and got these errors? For which language? I just checked redid `build_example()` and then rendered it, and that worked fine. You can check my steps in [this screencast](https://www.dropbox.com/s/ks5nbu9px1j0f19/tutorial.mov?dl=0).

Also, make sure you have the latest version of tutorial installed:

```R
update.packages("tutorial") # latest cran version
devtools::install_github("datacamp/tutorial") # latest development version
```

**Comment by rubenarslan** [comment]
I installed the latest Dev version, built the example and then tried it.
Sometimes it worked, but sometimes it didn't after a reload. It seemed
random.

**Comment by filipsch** [comment]
Hey @rubenarslan, you're sure you're doing that inside Chrome or another web browser?

**Comment by rubenarslan** [comment]
Yes I tried both Chrome and Safari.

**Comment by rubenarslan** [comment]
You can try it out yourself here: http://opencpu2.psych.bio.uni-goettingen.de/ocpu/tmp/x0d4f45777ec3d7e30bf3cb2b68631ea57bf3a72a27ec70bc9b9/files/knit.html

This is the request that fails:

> Request URL:https://multiplexer-prod.datacamp.com/input?sid=0595d4be848575e70f2a5968d16b7bc9&newCount=0
Request Method:POST
Status Code:403 Forbidden

> payload:
authentication_token:
"5a4b2ca7-60a8-4041-a9d7-ebd904825263"
command:"DC_DATA = ''↵DC_DATA = paste0(DC_DATA, '{"DC_RENDER_HEIGHT":198,"DC_RENDER_WIDTH":449,"DC_TYPE":"NormalExercise","DC_CODE":"plot(ran)","DC_ECHO":true,"DC_COMMAND":"console"}')↵execute(DC_DATA)"

**Comment by filipsch** [comment]
If you quickly switch between exercises on the example link you posted, you sometimes get the error message, but if you just click Run again, it's fine, no?

Seemed to work for me.

By the way, make sure to make `ran` explicitly available in the exercise, either in the sample code or in the `pre_exercise_code` (you can read more about it in the vignette).

**Comment by rubenarslan** [comment]
No, I almost always get the error message, without any switching and it's
not possible to make any progress because of that. That's why I haven't yet
figured out anything about making data available etc.
You get the error too but less often? Is it a race condition or a timeout
or something similar?

**Comment by rubenarslan** [comment]
It works maybe once in 20 times when I keep clicking the Run button.

Also, do I get this right: 
It's not possible to connect two consecutive chunks, but let the user play around in both? 
I.e. each chunk needs to be self-contained or have the code from all preceding chunks duplicated in a hidden "pre-exercise-code" chunk?
If so, it won't be useful for my purposes.

**Comment by filipsch** [comment]
Yes, all chunks need to be self-contained. Every chunk is something that stands on its own, and is independent of what happens inside other chunks.

**Comment by rubenarslan** [comment]
Too bad! If you did it differently, it would be very easy to turn an
existing knitr document into a step-by-step, this way not so much. In knitr
chunks depend on one another.

I could still use it for other things, let me know if you figure out how I
can avoid the timeout.

**Comment by witusj** [comment]
I have the same issue. After knitting the Rmd file I get a nice html file, but when running the exercise code, it states that the session has been disconnected. With a bit of patience and after repeatedly clicking the 'Run' button it finally runs. See this video for a demonstration: https://youtu.be/IFUw7GV6tas

I love the idea behind your tool and if this issue could be solved, it would be a quantum leap forward for me as a teacher. Truly revolutional!

**Comment by filipsch** [comment]
Hi @witusj I already elaborated on the issue in the `datacamp/datacamp-light` repo; let me know if it persists.

**Comment by filipsch** [comment]
Something that has to be addressed on datacamp-light

**Comment by filipsch** [comment]
Issue moved to [datacamp/datacamp-light #35](https://github.com/datacamp/datacamp-light/issues/35) via [**ZenHub**](https://www.zenhub.com/)
