### ISSUE TITLE
Wrong fiddle rendering

### ISSUE THREAD

**Issue by dfalbel** [datacamp/tutorial#18]
Wrong layout in datacamp tutorial.

I'm using the tutorial package here: https://github.com/curso-r/verao2017/blob/master/content/r-como-calculadora/exercicios.Rmd

But, It's rendering wrong in my site: 

![x](https://cloud.githubusercontent.com/assets/4706822/21485354/402ef96e-cb89-11e6-9dad-0703f6a1419e.PNG)

Here's [the link](https://curso-r.github.io/verao2017/r-como-calculadora/exercicios/).

Is there anyway I can configure the appearance of the fiddle? Thanks very much.

**Comment by filipsch** [comment]
Hi @dfalbel, when I try this out locally, there does not seem to be a problem. I get the [following result](https://www.dropbox.com/s/3yw4xg3fq28ltp1/Screenshot%202016-12-27%2008.46.10.png?dl=0). It looks like the CSS that your theme is using is interfering with the CSS used by DataCamp Light. Does the issue remain if you disable the theme completely and use no theme at all? This is going to be ugly, but then we'll know what's going on.

**Comment by dfalbel** [comment]
yeah! it's surely the css of my theme that is interfering with the one from datacamp :( Is there anyway I can fix this?

**Comment by EvertEt** [comment]
If you can find out which styles are interfering with DCL, you can make these more specific or make them exclude the main DCL CSS class (.datacamp-exercise).
Feel free to also tell us the conflicting styles so we can look if overriding them specifically will help more users in the future.

**Comment by dfalbel** [comment]
Thanks! I was able to solve by adding this to my site css:

```
.datacamp-exercise .dcl-content--tab li {
  list-style-type: none;
  margin-left: 0px;
  margin-top: 0px;
}

.datacamp-exercise .dcl-content--tab li:before {
  content: none;
}
```
I don't understand css very well, but I think the element `li` from the `datacamp-exercise` div was inheriting the list attributes from the `.article` class...

**Comment by filipsch** [comment]
Great news! Let me know if you bump into anything else out of the ordinary with datacamp light / tutorial!

**Comment by dfalbel** [comment]
Thanks!

**Comment by EvertEt** [comment]
@filipsch Should we add these styles as 'defaults' to our stylesheet so themes won't override them this easy anymore?
@dfalbel Thanks for the feedback!

**Comment by filipsch** [comment]
@EvertEt I think that's a good idea, feel free to do a PR!

**Comment by EvertEt** [comment]
Some standard and lots of hover colors also seem to be overridden on the webpage linked in the first post.

**Comment by dfalbel** [comment]
I didn't notice... It's fine for me like this, I don't understand enough of css to fix everything. One thing I noticed is that normally the console is placed side by side with the script instead of another tab.
