### ISSUE TITLE
'Powered by Datacamp' in the fiddle

### ISSUE THREAD

**Issue by dfalbel** [datacamp/tutorial#19]
If I use the following javascript code, I can remove the powered by datacamp div from the exercise fiddle.

`$(".powered-by-datacamp" ).remove();`

The question is, am I allowed to remove this?

Since my webpage has a lot of exercises, there are too many 'Powered by Datacamp' in my page. See : [link](https://curso-r.github.io/verao2017/r-como-calculadora/exercicios/). I would like to be able to put only one 'Powered by Datacamp' in the end of the page.

**Comment by filipsch** [comment]
@dfalbel you're free to update the appearance of the code chunks, but we would appreciate it if you keep some references to DataCamp on your web pages, so people know who is providing this technology. Thanks for checking!

**Comment by dfalbel** [comment]
Thanks @filipsch I removed all but the last 'Powered by DataCamp' in the page. Let me know if you think this is not enough. `tutorial` is a very nice package :)

**Comment by MT-David** [comment]
> If I use the following javascript code, I can remove the powered by datacamp div from the exercise fiddle.
> 
> `$(".powered-by-datacamp" ).remove();`
> 
> The question is, am I allowed to remove this?
> 
> Since my webpage has a lot of exercises, there are too many 'Powered by Datacamp' in my page. See : [link](https://curso-r.github.io/verao2017/r-como-calculadora/exercicios/). I would like to be able to put only one 'Powered by Datacamp' in the end of the page.

I have the same request. Do you know how to do this in RStudio? I do not have a lot of experience in JS. Thanks.
