### ISSUE TITLE
Incorrect rendering of accented characters

### ISSUE THREAD

**Issue by dfalbel** [datacamp/tutorial#20]
When using accented characters in exercises code comments, the sample code is ok:

![capturar](https://cloud.githubusercontent.com/assets/4706822/21507491/e734b844-cc5f-11e6-9297-95f51921c72b.PNG)

When I run the code, the accented characters are rendered wrong in the console

![capturar2](https://cloud.githubusercontent.com/assets/4706822/21507506/072a32f0-cc60-11e6-92d4-495d4d1d97c9.PNG)

Here a [reproducible example](https://github.com/curso-r/verao2017/blob/master/content/r-como-calculadora/exercicios.Rmd).

Thanks very much!

**Comment by dfalbel** [comment]
No problems! Thanks for great support.

**Comment by filipsch** [comment]
Something that has to be addressed on the `datacamp-light` project.

**Comment by filipsch** [comment]
Issue moved to [datacamp/datacamp-light #34](https://github.com/datacamp/datacamp-light/issues/34) via [**ZenHub**](https://www.zenhub.com/)
