### ISSUE TITLE
combining fiddle editors and evaluated code

### ISSUE THREAD

**Issue by larssk** [datacamp/tutorial#24]
Is there a way to combine datacamp-light fiddle editors with conventional rmarkdown code execution and evaluated code output in the same document? 

i.e. I want one code chunk as a datacamp-light editor, and another code chunk evaluated in the conventional way.

**Comment by filipsch** [comment]
Yes there is! 
If you use 

```R
tutorial::go_interactive()
```

at the top of your document, all chunks will automatically be converted into fiddles. If you don't want some chunks to be converted, you can use:

    ```{r, tut = FALSE}
    # this will render non-fiddly
    x <- 5
    ````

If you use

```R
tutorial::go_interactive(greedy = FALSE)
```

at the top of your document, all chunks will be standard markdown chunks. If you want some of the chunks to be converted:

    ```{r, tut = TRUE}
    # this will render fiddly
    x <- 5
    ````


Let me know if this worked. I'll keep this issue open, so I don't forget to add it to the docs.

**Comment by larssk** [comment]
Works like a charm. Thanks
