### ISSUE TITLE
Clearer documentation on required context

### ISSUE THREAD

**Issue by nathancarter** [datacamp/tutorial#5]
I just read a bunch of information about this project and the related [datacamp-light]() project, and after a bit of googling around, and experimenting on my own computer, I'm left with these unanswered questions.  This issue requests the available documentation be enhanced to address these use cases.  If you'd like to answer the questions here, I'm glad to edit the documentation to include your answers, and submit a pull request.

 * Do pages built with the `tutorial` package always establish a connection to [datacamp.com](https://www.datacamp.com/)?
 * Is the `testwhat` package used by `tutorial`?  If so, how does the fact that it requires proprietary R packages limit our use of `tutorial` in our own work?
 * Is there a way to get RStudio to use the `tutorial` package when knitting?
 * In rendered HTML viewed inside RStudio, should we expect the coding challenges to function?  (When using the method documented [here](https://github.com/datacamp/datacamp-light#using-the-javascript-library), the coding challenges just show the spinning datacamp logo indefinitely.)
 * If I want to email someone a `.rmd` file with coding challenges in it, and have them open the file in RStudio, knit it, and use it, should I include the code in [the Installation section](https://github.com/datacamp/tutorial#installing-the-package) somewhere in the `.rmd` file?  What about the code in [the Getting Started section](https://github.com/datacamp/tutorial#getting-started)?  (Those two sections don't really say where/when to execute their code.)

I realize this may not be the best place to post these questions, but the wiki was empty, and I can honestly classify them as a request for documentation expansion, so I'm doing so.  Thank you!

**Comment by vincentvankrunkelsven** [comment]
@nathancarter great questions! The maintainer of this package, @filipsch, is currently on holiday but will be back Tuesday. It's probably best that he answers your questions here and then expands the documentation further.

**Comment by nathancarter** [comment]
Great, thanks!

**Comment by filipsch** [comment]
Hi Nathan,

I added a wiki with your questions, a modest version of an FAQ.
https://github.com/datacamp/tutorial/wiki

About the indefinitely spinning datacamp logo: this shouldn't be happening. Could you send along the code snippet you're trying to mould into a DataCamp Light exercise? I can have a look.

I'll close this issue; feel free to make a new issue with the code snippet that's causing issues in RStudio.

Thanks!

**Comment by nathancarter** [comment]
Thank you very much!  I created the other issue, as requested:
https://github.com/datacamp/tutorial/issues/6
