### ISSUE TITLE
Example exercises not loading in RStudio viewer

### ISSUE THREAD

**Issue by nathancarter** [datacamp/tutorial#6]
Because RStudio cannot yet knit using `tutorial::render()` (that I know of), I created a `.Rmd` file that contains [the explicit HTML content from here](https://github.com/datacamp/datacamp-light#writing-the-html-block), and imports the DataCamp Light JavaScript library.  The result is [this `.Rmd` file](https://github.com/datacamp/tutorial/files/293688/datacamp-tutorial-pkg-test.Rmd.zip) (zipped so GitHub will accept it).  The issue is that knitting it inside RStudio, and seeing the result in RStudio's viewer, yields an indefinitely spinning DataCamp logo, rather than an interactive exercise.

**Comment by filipsch** [comment]
If you hit "Open in Browser" in RStudio's viewer pane, it opens your HTML file in the browser, and there it should work. I don't know why it doesn't work in RStudio's viewer pane, though. There might be technologies involved in the DataCamp Light library and the backend it communicates with that are not supported by the RStudio viewer.
I hope this doesn't affect your workflow to badly.

**Comment by nathancarter** [comment]
OK, thank you.

**Comment by filipsch** [comment]
This will soon be possible!

**Comment by nathancarter** [comment]
Glad to hear it!  I did see in the [bookdown](https://bookdown.org/yihui/bookdown/) docs (which are still in beta, I think) that custom build scripts will be expressible in YAML headers in Rmd files, and I think that's possible in the [current preview release](https://www.rstudio.com/products/rstudio/download/preview-release-notes/), but I'm not sure.  Looking forward to it, thanks!

**Comment by filipsch** [comment]
@nathancarter, the exercise should now render decently in RStudio's HTML viewer.
However, getting an R session inside the HTML doesn't seem to work on all platform. We think this is because the way cookies and requests are handled inside this browser instance. To actually experiment with the rendered code chunks, you'll have to click the 'view in browser' button. Hope this helps!
